---
version: '3.9'
services:
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=changeit
      - POSTGRES_USER=boauser
      - POSTGRES_DB=boadminDB
    command:
      - "postgres"
      - "-c"
      - "max_connections=100"
      - "-c"
      - "log_statement=all"
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "boadminDB", "-U", "boauser" ]
      timeout: 45s
      interval: 5s
      retries: 10
